### ISSUE TITLE
Cannot run from source

### ISSUE THREAD

**Issue by cugone** [OutpostUniverse/OPHD#1053] opened 2021-08-01 16:17 UTC
Cloning the repo fresh, pulling latest, and then attempting to run the game from within Visual Studio gets as far as trying to load the background music and fails with:

> Music::load() error: Failed loading vorbisfile.dll: The specified module could not be found.

**Comment by DanRStevens** [comment] 2021-08-01 23:19
You may want to search through previous issues on that. We've seen it before. You may find a solution in old threads.

https://github.com/OutpostUniverse/OPHD/search?q=vorbisfile.dll&type=issues

**Comment by madwax** [comment] 2021-08-12 08:11
The problem is vcpgk is not coping vorbis.dll,vorbisfile.dll and ogg.dll into the bin folder. As a fast work around copy the ones in the 0.8.3 release.

**Comment by DanRStevens** [comment] 2021-08-12 21:55
PR #505 added a PostBuild script that should copy those DLLs.

```batch
xcopy /y /d "!sourceDir!ogg.dll" "$(TargetDir)"
xcopy /y /d "!sourceDir!vorbis.dll" "$(TargetDir)"
xcopy /y /d "!sourceDir!vorbisfile.dll" "$(TargetDir)"
```

As far as I can tell, that's still intact.

Does the build log provide any indication if that step is running or failing in any way?

----

I'm curious if people having trouble with this may have a different `vcpkg` setup. I believe we generally assume `vcpkg integrate install` is being used, though I know cugone was experimenting with no system integration, and instead trying out a project specific integration. Is anyone else trying similar?

**Comment by ldicker83** [comment] 2021-08-12 23:12
> The problem is vcpgk is not coping vorbis.dll,vorbisfile.dll and ogg.dll into the bin folder. As a fast work around copy the ones in the 0.8.3 release.

Ah crud, I forgot about that. I just manually copied them once but that's annoying as hell.

I'll check in a clean install if that does the trick.

**Comment by madwax** [comment] 2021-08-12 23:20
I know when using vcpkg with cmake it does an auto dependency on your build products and copied them over. If it's the same via M$VS I would expect vorbis & ogg to be done automatically as they are linked but  not vorbisfile which appears to be runtime loaded.
I could be wrong about that

**Comment by ldicker83** [comment] 2021-08-12 23:30
The vorbis files are the only ones with vcpkg that aren't automatically copied. I'm not sure why that's the case but yeah, all the other dependencies are copied automatically.

Getting a VM set up to test out the related PR.

**Comment by cugone** [comment] 2021-08-13 00:10
What about just adding the .dlls to the repo directly?

**Comment by cugone** [comment] 2021-08-13 00:26
[The vcpkg integration page](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md) mentions that, during manual integration:
>
>Generally, to run any produced executables you will also need to either copy the needed DLL files to the same folder as your executable or prepend the correct `bin\` directory to your path.

**Comment by madwax** [comment] 2021-08-13 00:34
Keeping bin's in the repo is a very bad idea.   Nice to know that vcpkg via M$VS it runs the same powershell script as the cmake path.

**Comment by DanRStevens** [comment] 2021-08-13 03:09
>Keeping bin's in the repo is a very bad idea. Nice to know that vcpkg via M$VS it runs the same powershell script as the cmake path.

I agree 100%. Putting dependency binaries into source control is a very old school way of managing dependencies. It bloats the repo, and forces developers to download large binaries for systems they're not even using. Not to mention it provides poor tracking of dependent project versions, and poor upgrade support. If you're lucky, the project will either tag their binaries, so you know what version they were, or the person who committed them added an appropriate commit message, didn't make any typos or mistakes, and the project has clean enough history that you can actually easily find that commit message.

With package managers, it's documented much more explicitly in the source code. You can change one line of a small text file to update a version number, and it should all just work. At least, assuming you have the build system configured correctly for that system.

I'm really not interested in reverting to storing binaries in the repo. It's not the right solution.

> The vorbis files are the only ones with vcpkg that aren't automatically copied. I'm not sure why that's the case but yeah, all the other dependencies are copied automatically.

The `vcpkg` post build step will use `DUMPBIN` to scan the output file for statically linked or delayed loaded DLLs. It can only see libraries that are statically linked, such that an entry is created in the import table. The SDL2-mixer dependency dynamically links to certain libraries (using `LoadLibrary`) for format support. That means the `vcpkg` post build step scan won't see those dependencies, and won't know to copy the associated DLLs. That's why we added a manual post build step to copy those files.

If you're getting errors trying to run the executable, then there's something wrong with that manual post build step. Either it didn't run, or it didn't copy anything, or it failed with some kind of error. You should be checking the build log to see what that step is doing. I'm guess there was some kind of silent failure, since the complaint is about running the executable, rather than building the executable.

**Comment by DanRStevens** [comment] 2021-08-13 03:17
@madwax : I'm not entirely clear if you encountered the problem from the original post, or if you were just commenting to share your knowledge. I suppose, I should ask, did you run into this problem yourself? If so, could you give any details on if you use user wide integration of `vcpkg`, and if you noticed any build errors or strange messages in the post build step.

@cugone : I know you've been playing around with the `vcpkg` integration settings. Can you please check the build log for post build step messages. Maybe paste that section of the build log.

The custom post build step makes use of Vcpkg related variables. If you aren't using user wide integration, it's possible those variables aren't being set, and so the custom post build step might not work as expected.

**Comment by madwax** [comment] 2021-08-13 18:46
@DanRStevens Yes I did encounter the problem. As for installing vcpkg I used the normal clone, bootstrap-vcpkg.bat, vcpkg integrate install.  I installed all the packages as x86 and x64

**Comment by DanRStevens** [comment] 2021-08-13 20:30
It looks like the `VcpkgCurrentInstalledDir` variable is not set, which is causing the custom post build step to be skipped.

Custom post build step (see first `IF`):
```
SETLOCAL ENABLEDELAYEDEXPANSION

IF NOT "$(VcpkgCurrentInstalledDir)" == "" (
  IF "$(ConfigurationName)" == "Debug" (
    SET configDir="debug\"
  ) ELSE (
    SET configDir=""
  )

  SET sourceDir="$(VcpkgCurrentInstalledDir)%configDir%bin\"

  xcopy /y /d "!sourceDir!ogg.dll" "$(TargetDir)"
  xcopy /y /d "!sourceDir!vorbis.dll" "$(TargetDir)"
  xcopy /y /d "!sourceDir!vorbisfile.dll" "$(TargetDir)"
```

I checked the most recent build log for the Win 64 config of the `master` branch:
https://ci.appveyor.com/project/OPU/ophd/builds/40123986/job/yxidtgw2y06o0mdj

Here the `VcpkgCurrentInstalledDir` value is `""`:
> PostBuildEvent:
>   Copy OGG dependencies if vckpg present
>   SETLOCAL ENABLEDELAYEDEXPANSION
>   
>   IF NOT "" == "" (
>     IF "Release" == "Debug" (
>       SET configDir="debug\"
>     ) ELSE (
>       SET configDir=""
>     )
>   
>     SET sourceDir="%configDir%bin\"
>   
>     xcopy /y /d "!sourceDir!ogg.dll" "C:\projects\ophd\x64\Release\"
>     xcopy /y /d "!sourceDir!vorbis.dll" "C:\projects\ophd\x64\Release\"
>     xcopy /y /d "!sourceDir!vorbisfile.dll" "C:\projects\ophd\x64\Release\"
>   )
>   :VCEnd

That means the `xcopy` lines won't run.

I downloaded the associated artifact zip file, and confirmed those DLL files are missing, while the other `vcpkg` related files are present.

**Comment by DanRStevens** [comment] 2021-08-14 04:16
It seems the `$(VcpkgCurrentInstalledDir)` variable was removed. An equivalent value would be `$(VcpkgInstalledDir)$(VcpkgTriplet)\`.

Sources:
https://github.com/microsoft/vcpkg/issues/17632
https://github.com/microsoft/vcpkg/issues/12474

**Closed** 2021-08-15 21:43 UTC
