### ISSUE TITLE
Compiling latest from git

### ISSUE THREAD

**Issue by ray73864** [OutpostUniverse/OPHD#736] opened 2020-12-25 21:25 UTC
Attempting to compile the last git repo using Visual Studio, I followed all the instructions on the wiki with regards to 'building from source' which includes the vcpkg steps.

When I compile however, I get the following error:

```
Error	MSB3073	The command "SETLOCAL ENABLEDELAYEDEXPANSION

IF NOT "G:\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\" == "" (
  IF "Release" == "Debug" (
    SET configDir="debug\"
  ) ELSE (
    SET configDir=""
  )

  SET sourceDir="G:\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\%configDir%bin\"

  xcopy /y /d "!sourceDir!ogg.dll" "C:\Users\ray\Source\Repos\OPHD\x64\Release\"
  xcopy /y /d "!sourceDir!vorbis.dll" "C:\Users\ray\Source\Repos\OPHD\x64\Release\"
  xcopy /y /d "!sourceDir!vorbisfile.dll" "C:\Users\ray\Source\Repos\OPHD\x64\Release\"
)
:VCEnd" exited with code 4.
```

**Comment by DanRStevens** [comment] 2020-12-26 04:35
Hi, thank you for the report.

----

The problem appears to be from the `xcopy` command from the Post-Build event script in the project file:
```
    <PostBuildEvent>
      <Command>SETLOCAL ENABLEDELAYEDEXPANSION

IF NOT "$(VcpkgCurrentInstalledDir)" == "" (
  IF "$(ConfigurationName)" == "Debug" (
    SET configDir="debug\"
  ) ELSE (
    SET configDir=""
  )

  SET sourceDir="$(VcpkgCurrentInstalledDir)%configDir%bin\"

  xcopy /y /d "!sourceDir!ogg.dll" "$(TargetDir)"
  xcopy /y /d "!sourceDir!vorbis.dll" "$(TargetDir)"
  xcopy /y /d "!sourceDir!vorbisfile.dll" "$(TargetDir)"
)</Command>
      <Message>Copy OGG dependencies if vckpg present</Message>
    </PostBuildEvent>
```

@Brett208: You may be more familiar with this code than I am.

Relevant documentation:
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/xcopy

Exit code 4:
> Initialization error occurred. There is not enough memory or disk space, or you entered an invalid drive name or invalid syntax on the command line.

Perhaps `%sourceDir%` was intended, rather than `!sourceDir!`? I've never seen that syntax before.

**Comment by ray73864** [comment] 2020-12-26 08:35
I tried changing it from ```!sourceDir!``` to ```$(sourceDir$)``` but it didn't make any difference.

And then if I search the cloned repo for 'ogg.dll', and 'vorbis.dll' and 'vorbisfile.dll', none of them are in the cloned repo at all, so i'm not sure where it is supposed to be getting these 3 files from.

I could just download the release build, but I wanted to play it with an up to date copy, the release build is about 18months old compared to the most recent git commit of only a few months ago.

**Comment by ray73864** [comment] 2020-12-26 08:37
I even checked the entire 'vcpkg' directory and that doesn't have those 3 files either.

**Comment by DanRStevens** [comment] 2020-12-26 08:59
I just tried changing `!sourceDir!` to `%sourceDir%`, but got the error you described. Curiously the builds are passing on the continuous integration servers using the old syntax.

Old syntax build log: https://ci.appveyor.com/project/OPU/ophd/builds/36817353/job/0fw45nhoau7qy1mm
New syntax build log: https://ci.appveyor.com/project/OPU/ophd/builds/37002619/job/8huh36c76s2k3fww

----

From the original pasted error text, the scripted line:
```
SET sourceDir="$(VcpkgCurrentInstalledDir)%configDir%bin\"
```
Expands to:
```
SET sourceDir="G:\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\%configDir%bin\"
```
That means the DLL files should be located in:
`G:\vcpkg\installed\x64-windows\%configDir%bin\`
Where `%configDir%` = `""` for release builds, or `"debug\"` for debug builds.

If the files don't exist in there, it may be an issue running the `vcpkg` install steps. That is generally done by running the batch file:
```
nas2d-core/InstallVcpkgDeps.bat
```

(I haven't checked the Wiki in ages, so instructions in there may be old).

**Comment by ray73864** [comment] 2020-12-26 09:44
Edited ```nas2d-core\InstallVcpkgDeps.bat``` so that it pointed to where I have vcpkg installed (since vcpkg isn't in the PATH variable), I can see ogg.dll, etc... in x86-windows\bin, and now I can see it in x64-windows\bin too.

I don't remember that particular .bat file being on the wiki saying to run it.

Reset my postbuild stuff back to what it originally was.

Re-running the 'build solution', and now it has a whole stack more errors in it than it had before :(

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'SDL2/SDL_mixer.h': No such file or directory	NAS2D	C:\Users\ray\Source\Repos\OPHD\nas2d-core\NAS2D\Resources\Sound.cpp	17	
Error	C1083	Cannot open include file: 'SDL2/SDL_mixer.h': No such file or directory	NAS2D	C:\Users\ray\Source\Repos\OPHD\nas2d-core\NAS2D\Resources\Music.cpp	16	
Error	C1083	Cannot open include file: 'SDL2/SDL_mixer.h': No such file or directory	NAS2D	C:\Users\ray\Source\Repos\OPHD\nas2d-core\NAS2D\Mixer\MixerSDL.cpp	22	
Error	LNK2001	unresolved external symbol Mix_VolumeMusic	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_FadeOutMusic	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_HookMusicFinished	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_OpenAudio	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_Volume	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_PauseMusic	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_Pause	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_ResumeMusic	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_CloseAudio	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_PlayChannelTimed	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_FadeInMusic	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_HaltChannel	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_PlayingMusic	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_Resume	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_HaltMusic	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(MixerSDL.obj)	1	
Error	LNK2001	unresolved external symbol Mix_FreeMusic	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(Music.obj)	1	
Error	LNK2001	unresolved external symbol Mix_LoadMUS_RW	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(Music.obj)	1	
Error	LNK2001	unresolved external symbol Mix_FreeChunk	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(Sound.obj)	1	
Error	LNK2001	unresolved external symbol Mix_LoadWAV_RW	OPHD	C:\Users\ray\Source\Repos\OPHD\OPHD\NAS2D.lib(Sound.obj)	1	
Error	LNK1120	19 unresolved externals	OPHD	C:\Users\ray\Source\Repos\OPHD\x64\Release\OPHD.exe	1	
```

**Comment by ray73864** [comment] 2020-12-26 09:45
I would just be happy for a new released version that isn't over a year old, then I wouldn't have to go down this path.

**Comment by DanRStevens** [comment] 2020-12-26 10:05
Looks like you have a `vcpkg` issue. I'm guessing `vcpkg` isn't integrated into your environment, hence why it wasn't available on the path.

The first step, which it seems you'd now accomplished, is to have `vcpkg` download and compile the dependencies. The second step, which is still a problem, is to compile the OPHD source against those dependencies.

The `vcpkg` tooling is used to find the headers for `vcpkg` installed dependencies when compiling, as well as to find the compiled libraries files for those dependencies when linking. The errors you listed are because `vcpkg` tooling isn't setup to find the headers or compiled libraries. You may want to consult the `vcpkg` reference about integrating it into your environment.

https://vcpkg.readthedocs.io/en/latest/examples/installing-and-using-packages/

See "Step 2", where they use `vcpkg integrate install`.

----

With that said, if all you want is the compiled binaries, every continuous integration build stores the executable file as one of the build artifacts. These are mainly for debugging, though should be publicly accessible even if there is no formal release for that build. It's just a little harder to find.

From the main GitHub code page, find the green check mark indicating a successful continuous integration build, click on it and scroll to the desired build (the Windows one has a blue icon) and follow the "details" link, select the platform you want (generally the 64-bit build these days), and then go to the artifacts tab. The download will be on that page. It'll be the smaller package, not the one with the debug symbols.

Here's the most recent build:
https://ci.appveyor.com/project/OPU/ophd/builds/36817353/job/0fw45nhoau7qy1mm/artifacts

**Comment by DanRStevens** [comment] 2020-12-26 10:35
@Brett208: This looks like it may have been a `vcpkg` setup issue. Our outdated Wiki instructions may have been to blame. Still curious about the `!sourceDir!` syntax, though that doesn't seem to have been the problem.

Maybe there is a way we can detect when `vcpkg` isn't integrated into the environment, and issue a meaningful error message. Right now the current failure mode doesn't provide any helpful hints as to what went wrong. It may be possible for the project file to detect some Vcpkg provided variable, and if not present, issue an error message to the build console, along with instructions on how to fix it.

Or would it be bad to tie the project file to a particular dependency manager?

**Comment by ray73864** [comment] 2020-12-26 11:32
I had already done the 'vcpkg integrate install' the other day before I opened this issue originally, so i'm not sure why it's not set on the path environment variable.

Basically followed the wiki to the letter with setting everything up, it said I could install vcpkg where-ever I wanted to, and I figured since my G drive has more space on it than my C drive, I would put it there.

**Comment by ray73864** [comment] 2020-12-26 11:34
I even did the optional build steps after the integration.

**Comment by DanRStevens** [comment] 2020-12-26 11:48
It's been a while since I've used a Windows environment, so I'm afraid I'm stuck speculating about the problem. The only Windows environment I really have access to these days are the continuous integration builds on AppVeyor, and their build images comes with `vcpkg` already installed and setup. If it's a `vcpkg` setup or integration issue, which it rather looks like, I'm not really in a good position to test.

As it sounds like you did indeed run the `vcpkg integrate install` command, my best guess might be if it was run without administrator access. I'm not sure if there is any error message in such a case, though I'm pretty sure it won't have lasting effect without administrator access. You mentioned running it yesterday, so perhaps you rebooted since you ran the command. Maybe it'll quietly only do session setup without administrator access, rather than permanent setup? Kind of a wild guess though.

I may need someone else to investigate if it's a `vcpkg` setup issue.

**Comment by Brett208** [comment] 2020-12-26 16:40
@DanRStevens or @ldicker83,

It sounds like @ray73864 is more interested in the most recent build from master to play or test as opposed to building up the infrastructure to compile from source. 

It is common on other projects I've seen to have a link to pull the most recent build artifacts from the master tree for beta testing or other purposes. 

Have we looked into maybe putting a link on the wiki or in the master readme for OPHD that links to the most recent build artifacts? Maybe just the Windows build to start with since it is the most common.

**Comment by Brett208** [comment] 2020-12-26 16:47
@DanRStevens,

If I recall correctly, the exclamation mark syntax `!sourceDir!` affects the order of when variables expand for Windows command line and batch script arguments. The default behavior without the ! sometimes causes unexpected results although I am not remembering the details without doing some research. 

Since the automated build is working, I'm assuming the wiki instructions are either out of sync or maybe not clear enough.

@ray73864, I noticed you are using the G drive for vcpkg in the snippets above. Are you installing vcpkg on a different drive from where you are compiling OPHD? I haven't experimented with this before, although I suppose it should work?

**Comment by ray73864** [comment] 2020-12-26 20:58
I am, yes.

vcpkg is on the G drive, and OPHD is on the C drive.

**Comment by ray73864** [comment] 2020-12-26 21:15
OK, So I deleted the repo completely, came back here to github, clicked on 'code' then on the 'Open in Visual Studio', cloned it to the G drive too, opened it, tried to recompile, kept complaining about outdated pdb files, etc...

Closed Visual Studio, opened command prompt and did the vcpkg bootstrap thing again and then the integrate again.

Deleted the temporary folder from the OPHD directory, opened the solution, redid the 'build solution', it took a little bit but this time it has 'build succeeded'.

**Comment by DanRStevens** [comment] 2020-12-27 04:33
@Brett208, I think you're right about having a link to the latest build.

Though it does raise the question of where to host it. If we direct link to AppVeyor, and the project goes idle, AppVeyor will eventually delete old artifacts, and the link will be broken. Not sure where else to host it. Unless we created a GitHub release for the latest build, and marked it as such. That might give it more of an official look though, which we might want to avoid.

Of course Leeor was thinking of packaging a new release soon, so that might be at least a temporary solution.

----

Ahh, that clicks now. I found some info on `EnableDelayedExpansion`, which explains the `!variable!` syntax:
https://ss64.com/nt/delayedexpansion.html

----

@ray73864, sounds like we have a bit of work to make the experience a little more smooth. For some reason I thought we had designed it to work so data was accessible in either the deployment directory layout, or the development directory layout. It seems the development directory layout doesn't work though.

Glad you got it working though.

**Comment by ldicker83** [comment] 2020-12-31 02:01
That sounds like a debugger setting which is usually in the user options. I thought I had that corrected.

I plan to have a release put together in the next day or so. Just tidying somethings up and then it'll be good to go.

Sorry I haven't been too involved -- this time of year is ridiculously busy at work so I tend to kind of fall off the radar until after the new year.

**Comment by ldicker83** [comment] 2021-01-01 06:29
I looked into this after setting up a virtual machine with a clean install of Windows and Visual Studio. vcpkg really needs to be set up in the environment path or the whole build process breaks. I noted this in #737.

I'll be updating the build instructions and probably releasing a clean build later today. Keep an eye out!

**Comment by ldicker83** [comment] 2021-01-01 18:45
Have released a new version of OPHD just now: https://forum.outpost2.net/index.php/topic,6371.0.html

Can get from the releases tab. The 23MB zip archive -- that's the complete release with data assets.

**Comment by DanRStevens** [comment] 2021-05-23 04:56
We should probably close this. I think the new release solved the immediate problem of getting an up-to-date executable. As for the compiling difficulties, there are two opened issues to address them:
- #737
- https://github.com/lairworks/nas2d-core/issues/373

**Closed** 2021-05-23 04:56 UTC
Labels: discussion
